### ISSUE TITLE
遍历到子目录里面, 里面是空的 就停了

### ISSUE THREAD

**Issue by kalsolio** [gordonwalkedby/shimo-export#1]

**Comment by kalsolio** [comment]
![image](https://user-images.githubusercontent.com/14342288/115657978-72093900-a36a-11eb-8508-ce3feef8098e.png)

**Comment by gordonwalkedby** [comment]
卧槽！是真的！！    
请您稍等，我下班回家马上修bug！

**Comment by gordonwalkedby** [comment]
已经修复了，您看一下行不行？   
我在空的文件夹里丢了一个 txt 来占位置，不然的话导出的 zip 里是没有这个空文件夹的。    
[greasyfork](https://greasyfork.org/scripts/423544-%E7%9F%B3%E5%A2%A8%E6%96%87%E6%A1%A3%E6%89%B9%E9%87%8F%E5%AF%BC%E5%87%BA)
