### ISSUE TITLE
插件从5/7号之后不能使用

### ISSUE THREAD

**Issue by TyrionCantCode** [gordonwalkedby/shimo-export#2]
下载提示：

上午9:30:10 | 下载异常：Refused to connect to "https://files.shimonote.com/shimo-export/S55ctR5REfIj03Jp.xlsx?auth_key=1620437410-qIPRGOHEARpV6Cez-0-d242e82192f1b8d7dd511fbf94ba435d&response-content-disposition=attachment%3B+filename%3D%22%25E5%2591%25A8%25E7%2591%25B6%25E7%25BA%25A2.xlsx%22%3B+filename%2A%3DUTF-8%27%27%25E5%2591%25A8%25E7%2591%25B6%25E7%25BA%25A2.xlsx": Request was redirected to a not whitelisted URL
上午9:30:10 | 重试：1

但实际上这个链接手动复制到浏览器是可以下载的

**Comment by TyrionCantCode** [comment]
`上午9:30:01 | 这里是戈登走過去编写的石墨文档批量导出工具。希望可以帮助到你。祝愿你每天开心。少加班，多休息。
 QWQ
上午9:30:01 | 今天是：2021/5/8
上午9:30:01 | 开始导出工作
上午9:30:01 | 扫描子文件夹和子文件中...
上午9:30:01 | 开始扫描文件夹：起点
上午9:30:02 | 扫描结束，统计信息：
上午9:30:02 | 总文件数量：2
上午9:30:02 | 实际可导出文件数量：2
上午9:30:02 | 表格：2
上午9:30:02 | 下面开始下载要导出的文件
上午9:30:02 | 进度：0.0% 起点/周瑶红.xlsx
上午9:30:10 | 下载异常：Refused to connect to "https://files.shimonote.com/shimo-export/S55ctR5REfIj03Jp.xlsx?auth_key=1620437410-qIPRGOHEARpV6Cez-0-d242e82192f1b8d7dd511fbf94ba435d&response-content-disposition=attachment%3B+filename%3D%22%25E5%2591%25A8%25E7%2591%25B6%25E7%25BA%25A2.xlsx%22%3B+filename%2A%3DUTF-8%27%27%25E5%2591%25A8%25E7%2591%25B6%25E7%25BA%25A2.xlsx": Request was redirected to a not whitelisted URL
上午9:30:10 | 重试：1
上午9:30:17 | 下载异常：Refused to connect to "https://files.shimonote.com/shimo-export/SOpSs9GW7gc4GnXi.xlsx?auth_key=1620437417-BqHPsLu03SZY4kQq-0-ce106729c616016e32e78e72f39193cb&response-content-disposition=attachment%3B+filename%3D%22%25E5%2591%25A8%25E7%2591%25B6%25E7%25BA%25A2.xlsx%22%3B+filename%2A%3DUTF-8%27%27%25E5%2591%25A8%25E7%2591%25B6%25E7%25BA%25A2.xlsx": Request was redirected to a not whitelisted URL
上午9:30:17 | 重试：2
上午9:30:25 | 下载异常：Refused to connect to "https://files.shimonote.com/shimo-export/0uqnWvRXKTLjfUIB.xlsx?auth_key=1620437425-25XlqXmVXsjQ68vI-0-4f33096b498e9d307a049d2a1d8bbcee&response-content-disposition=attachment%3B+filename%3D%22%25E5%2591%25A8%25E7%2591%25B6%25E7%25BA%25A2.xlsx%22%3B+filename%2A%3DUTF-8%27%27%25E5%2591%25A8%25E7%2591%25B6%25E7%25BA%25A2.xlsx": Request was redirected to a not whitelisted URL
上午9:30:25 | 重试：3
上午9:30:35 | 返回超时！
上午9:30:35 | 失败，跳过：起点/周瑶红
上午9:30:35 | 进度：50.0% 起点/杨文静.xlsx
上午9:30:44 | 下载异常：Refused to connect to "https://files.shimonote.com/shimo-export/otU8vNJty21DBBme.xlsx?auth_key=1620437444-4yHb7EK067d3mblU-0-53c3b265510e9ae9798832afd3ec26af&response-content-disposition=attachment%3B+filename%3D%22%25E6%259D%25A8%25E6%2596%2587%25E9%259D%2599.xlsx%22%3B+filename%2A%3DUTF-8%27%27%25E6%259D%25A8%25E6%2596%2587%25E9%259D%2599.xlsx": Request was redirected to a not whitelisted URL
上午9:30:44 | 重试：1
上午9:30:49 | 返回异常：429 {"requestId":"c5c5f2404d5265a28624b1946fa1e51c","error":"Rate limit exceeded, retry in 17 seconds","errorCode":0}
上午9:30:49 | 石墨限制，等待到这之后再继续：上午9:31:07
上午9:31:08 | 重试：2
上午9:31:17 | 下载异常：Refused to connect to "https://files.shimonote.com/shimo-export/E6pp22g97UScPnzh.xlsx?auth_key=1620437477-V8zgUVILxPGYkz76-0-40ea366effa08e964d89c807415c5667&response-content-disposition=attachment%3B+filename%3D%22%25E6%259D%25A8%25E6%2596%2587%25E9%259D%2599.xlsx%22%3B+filename%2A%3DUTF-8%27%27%25E6%259D%25A8%25E6%2596%2587%25E9%259D%2599.xlsx": Request was redirected to a not whitelisted URL
上午9:31:17 | 重试：3
上午9:31:26 | 下载异常：Refused to connect to "https://files.shimonote.com/shimo-export/R4Cp42eDhTkaSAWZ.xlsx?auth_key=1620437486-r39tqWZjs4VlovxJ-0-512d0f8bb6caaaea5346f4fdf29d3d21&response-content-disposition=attachment%3B+filename%3D%22%25E6%259D%25A8%25E6%2596%2587%25E9%259D%2599.xlsx%22%3B+filename%2A%3DUTF-8%27%27%25E6%259D%25A8%25E6%2596%2587%25E9%259D%2599.xlsx": Request was redirected to a not whitelisted URL
上午9:31:26 | 失败，跳过：起点/杨文静
上午9:31:26 | 导出工作结束，失败数：2
上午9:31:26 | 起点/周瑶红
起点/杨文静

上午9:31:26 | 总用时：1.4 分钟。
上午9:31:26 | 正在生成 zip 文件
`

**Comment by gordonwalkedby** [comment]
您好！   
我发现是石墨官方把提供下载的网址域名给换了。  
原来是 smcdn.cn ，现在换成了 shimonote.com  ，我现在修好了脚本，自己测试了是没有问题的。   
请您更新到 v1.2  试试    
更新链接：   
 https://greasyfork.org/zh-CN/scripts/423544-%E7%9F%B3%E5%A2%A8%E6%96%87%E6%A1%A3%E6%89%B9%E9%87%8F%E5%AF%BC%E5%87%BA

**Comment by TyrionCantCode** [comment]
> 您好！
> 我发现是石墨官方把提供下载的网址域名给换了。
> 原来是 smcdn.cn ，现在换成了 shimonote.com ，我现在修好了脚本，自己测试了是没有问题的。
> 请您更新到 v1.2 试试
> 更新链接：
> https://greasyfork.org/zh-CN/scripts/423544-%E7%9F%B3%E5%A2%A8%E6%96%87%E6%A1%A3%E6%89%B9%E9%87%8F%E5%AF%BC%E5%87%BA
> 
> 我删除了您的一条回复，是因为您的日志里包含有您的隐私信息。

更新完可以使用，感谢您
