### ISSUE TITLE
批量下载返回异常：500

### ISSUE THREAD

**Issue by Jerrywang77** [gordonwalkedby/shimo-export#4]
上午12:56:56 | 返回异常：500 {"requestId":"117f525ba3638e0774e57370254571b7","error":"Internal Server Error","errorCode":0}

**Comment by gordonwalkedby** [comment]
500的话应该是石墨本身的导出功能故障了。     
我自己现在试了也没有发现什么异常。    
有没有别的可疑点？

**Comment by ihomentMickChen** [comment]
500时候没有reject重新尝试

**Comment by gordonwalkedby** [comment]
@ihomentMickChen  谢谢你！！！    
我做了 v1.3 ，请试一下能不能行。现在遇到 200 以外的情况会自动重试的。        
@Jerrywang77 
https://greasyfork.org/zh-CN/scripts/423544-%E7%9F%B3%E5%A2%A8%E6%96%87%E6%A1%A3%E6%89%B9%E9%87%8F%E5%AF%BC%E5%87%BA

**Comment by ihomentMickChen** [comment]
然而我现在要放弃使用了，我拉取170个文件成功后zip包无法下载，一直正在生成 zip 文件中

**Comment by ihomentMickChen** [comment]
下午5:11:31 | 这里是戈登走過去编写的石墨文档批量导出工具。希望可以帮助到你。祝愿你每天开心。少加班，多休息。
QWQ
下午5:11:31 | 今天是：2021/7/1
下午5:11:31 | 开始导出工作
下午5:11:31 | 扫描子文件夹和子文件中...
下午5:11:31 | 开始扫描文件夹：起点
下午5:11:32 | 无法解析链接：/sheet/3KKnvKD0oZIPiXNi
下午5:11:32 | 无法解析链接：/sheet/t83YhyPYwRwjvk3X
下午5:11:32 | 开始扫描文件夹：起点/iOS小组
下午5:11:33 | 开始扫描文件夹：起点/UI bugs
下午5:11:34 | 开始扫描文件夹：起点/iOS小组/例会
下午5:11:36 | 开始扫描文件夹：起点/UI bugs/V4.3
下午5:11:37 | 开始扫描文件夹：起点/UI bugs/V4.2.0
下午5:11:38 | 开始扫描文件夹：起点/UI bugs/V4.1.0
下午5:11:39 | 开始扫描文件夹：起点/UI bugs/V4.0
下午5:11:41 | 开始扫描文件夹：起点/UI bugs/v3.9.0
下午5:11:42 | 开始扫描文件夹：起点/UI bugs/V3.8
下午5:11:43 | 开始扫描文件夹：起点/UI bugs/V3.7
下午5:11:45 | 开始扫描文件夹：起点/UI bugs/V3.6
下午5:11:46 | 开始扫描文件夹：起点/UI bugs/V3.5
下午5:11:47 | 开始扫描文件夹：起点/UI bugs/V3.4.0
下午5:11:48 | 开始扫描文件夹：起点/UI bugs/暗夜模式
下午5:11:50 | 开始扫描文件夹：起点/UI bugs/V3.3.0
下午5:11:51 | 开始扫描文件夹：起点/UI bugs/V3.1.0
下午5:11:52 | 开始扫描文件夹：起点/UI bugs/V1.0~V2.4
下午5:11:53 | 开始扫描文件夹：起点/UI bugs/V3.0
下午5:11:55 | 开始扫描文件夹：起点/iOS小组/例会/存档
下午5:11:56 | 开始扫描文件夹：起点/UI bugs/V1.0~V2.4/V2.4
下午5:11:57 | 开始扫描文件夹：起点/UI bugs/V1.0~V2.4/V2.3
下午5:11:58 | 开始扫描文件夹：起点/UI bugs/V1.0~V2.4/V2.2
下午5:12:00 | 开始扫描文件夹：起点/UI bugs/V1.0~V2.4/V2.1
下午5:12:01 | 开始扫描文件夹：起点/UI bugs/V1.0~V2.4/V2.0
下午5:12:02 | 开始扫描文件夹：起点/UI bugs/V1.0~V2.4/V1.9
下午5:12:03 | 开始扫描文件夹：起点/UI bugs/V1.0~V2.4/V1.8
下午5:12:05 | 开始扫描文件夹：起点/UI bugs/V1.0~V2.4/V1.7
下午5:12:06 | 开始扫描文件夹：起点/UI bugs/V1.0~V2.4/V1.6
下午5:12:07 | 开始扫描文件夹：起点/UI bugs/V1.0~V2.4/V1.5
下午5:12:08 | 开始扫描文件夹：起点/UI bugs/V1.0~V2.4/V1.4
下午5:12:10 | 开始扫描文件夹：起点/UI bugs/V1.0~V2.4/V1.3.2
下午5:12:11 | 开始扫描文件夹：起点/UI bugs/V1.0~V2.4/V1.3.0
下午5:12:12 | 开始扫描文件夹：起点/UI bugs/V1.0~V2.4/V1.2.1
下午5:12:13 | 开始扫描文件夹：起点/UI bugs/V1.0~V2.4/V1.2
下午5:12:14 | 开始扫描文件夹：起点/UI bugs/V1.0~V2.4/V1.1
下午5:12:16 | 开始扫描文件夹：起点/UI bugs/V1.0~V2.4/V1.0
下午5:12:17 | 扫描结束，统计信息：
下午5:12:17 | 总文件数量：130
下午5:12:17 | 石墨文档有速度限制，1分钟最多只能导出 5 个文件，相当于 12 秒一个，所以说预计完成导出时间是：2021/7/1下午5:39:17
下午5:12:17 | 实际可导出文件数量：130
下午5:12:17 | 表格：26
下午5:12:17 | 普通文档：104
下午5:12:17 | 下面开始下载要导出的文件
下午5:12:17 | 进度：0.0% 起点/APP专项测试.xlsx
下午5:12:33 | 进度：0.8% 起点/V3.0 字体样式表.docx
下午5:14:57 | 进度：1.5% 起点/V3.0 UI设计样式表.docx
下午5:17:16 | 进度：2.3% 起点/iOS-发版提测记录表.xlsx
下午5:17:32 | 进度：3.1% 起点/iOS多语言.xlsx
下午5:17:48 | 进度：3.8% 起点/App 版本迭代测试计划.xlsx
下午5:18:05 | 进度：4.6% 起点/用户中心开发机采购.xlsx
下午5:18:22 | 进度：5.4% 起点/iOS Fastlane 自动打包.docx
下午5:18:38 | 进度：6.2% 起点/一分钟，了解石墨文档 .docx
下午5:18:54 | 进度：6.9% 起点/iOS小组/副本 APP专项测试.xlsx
下午5:19:11 | 进度：7.7% 起点/iOS小组/Govee Home 重构.docx
下午5:19:26 | 进度：8.5% 起点/iOS小组/无标题.xlsx
下午5:19:43 | 进度：9.2% 起点/iOS小组/iOS Fastlane 自动打包.docx
下午5:19:58 | 进度：10.0% 起点/iOS小组/例会/2020-06-08.xlsx
下午5:20:14 | 进度：10.8% 起点/UI bugs/V4.3/V4.3.0 iOS_UI bugs.docx
下午5:21:08 | 进度：11.5% 起点/UI bugs/V4.3/V4.3.0 Android UI bugs.docx
下午5:22:20 | 进度：12.3% 起点/UI bugs/V4.3/V4.3 H5 UI bugs.docx
下午5:22:45 | 进度：13.1% 起点/UI bugs/V4.3/AI图片灯效库 H5 UI bugs.docx
下午5:23:15 | 进度：13.8% 起点/UI bugs/V4.3/声音库 H5 UI bugs.docx
下午5:23:34 | 进度：14.6% 起点/UI bugs/V4.2.0/母亲节 H5 UI bugs.docx
下午5:23:56 | 进度：15.4% 起点/UI bugs/V4.2.0/V4.2 H5页面UI bugs.docx
下午5:24:24 | 进度：16.2% 起点/UI bugs/V4.2.0/V4.2.0 iOS_UI bugs.docx
下午5:25:13 | 进度：16.9% 起点/UI bugs/V4.2.0/V4.2.0 Android UI bugs.docx
下午5:25:56 | 进度：17.7% 起点/UI bugs/V4.1.0/填字游戏 H5 UI bugs.docx
下午5:26:17 | 进度：18.5% 起点/UI bugs/V4.1.0/V4.1 H5页面UI bugs.docx
下午5:26:38 | 进度：19.2% 起点/UI bugs/V4.1.0/V4.1.0 Android UI bugs.docx
下午5:27:35 | 进度：20.0% 起点/UI bugs/V4.1.0/V4.1.0 iOS_UI bugs.docx
下午5:28:43 | 进度：20.8% 起点/UI bugs/V4.0/V4.0.0 Android UI bugs.docx
下午5:29:14 | 进度：21.5% 起点/UI bugs/V4.0/V4.0.0 iOS_UI bugs.docx
下午5:29:47 | 进度：22.3% 起点/UI bugs/v3.9.0/RGBIC 星球H5 UI bugs.docx
下午5:30:08 | 进度：23.1% 起点/UI bugs/v3.9.0/V3.9 H5页面UI bugs.docx
下午5:30:27 | 进度：23.8% 起点/UI bugs/v3.9.0/V3.9.0 iOS_UI bugs.docx
下午5:30:56 | 进度：24.6% 起点/UI bugs/v3.9.0/V3.9 Android UI bugs.docx
下午5:31:26 | 进度：25.4% 起点/UI bugs/v3.9.0/圣诞节H5 UI bugs.docx
下午5:32:02 | 进度：26.2% 起点/UI bugs/V3.8/V3.8 H5页面UI bugs.docx
下午5:32:18 | 进度：26.9% 起点/UI bugs/V3.8/黑五 UI bugs.docx
下午5:32:42 | 进度：27.7% 起点/UI bugs/V3.8/V3.8.0 iOS_UI bugs.docx
下午5:33:43 | 进度：28.5% 起点/UI bugs/V3.8/V3.8 Android UI bugs.docx
下午5:34:52 | 进度：29.2% 起点/UI bugs/V3.8/闯关赢积分 UI bugs.docx
下午5:35:13 | 进度：30.0% 起点/UI bugs/V3.7/万圣节2020 UI bugs.docx
下午5:35:49 | 进度：30.8% 起点/UI bugs/V3.7/V3.7.0 iOS_UI bugs.docx
下午5:36:19 | 进度：31.5% 起点/UI bugs/V3.7/V3.7 H5页面UI bugs.docx
下午5:36:36 | 进度：32.3% 起点/UI bugs/V3.7/V3.7 Android UI bugs.docx
下午5:37:06 | 进度：33.1% 起点/UI bugs/V3.6/一周签到打卡 UI bugs.docx
下午5:37:24 | 进度：33.8% 起点/UI bugs/V3.6/iOS_UI bugs V3.6.0.docx
下午5:37:51 | 进度：34.6% 起点/UI bugs/V3.6/V3.6 H5页面UI bugs.docx
下午5:38:09 | 进度：35.4% 起点/UI bugs/V3.6/V3.6 Android UI bugs.docx
下午5:38:44 | 进度：36.2% 起点/UI bugs/V3.5/副本 Android_UI bugs V3.5.0.docx
下午5:39:12 | 进度：36.9% 起点/UI bugs/V3.5/H5_UI bugs V3.5.0.docx
下午5:39:33 | 进度：37.7% 起点/UI bugs/V3.5/iOS_UI bugs V3.5.0.docx
下午5:39:59 | 进度：38.5% 起点/UI bugs/V3.5/Android_UI bugs V3.5.0.docx
下午5:40:18 | 进度：39.2% 起点/UI bugs/V3.4.0/H5_UI bugs v3.4.0.docx
下午5:40:36 | 进度：40.0% 起点/UI bugs/V3.4.0/副本 Android_UI bugs v3.4.0.docx
下午5:41:02 | 进度：40.8% 起点/UI bugs/V3.4.0/iOS_UI bugs v3.4.0.docx
下午5:41:31 | 进度：41.5% 起点/UI bugs/V3.4.0/Android_UI bugs v3.4.0.docx
下午5:41:47 | 进度：42.3% 起点/UI bugs/暗夜模式/副本 iOS 暗夜模式的UI bugs.docx
下午5:42:18 | 进度：43.1% 起点/UI bugs/暗夜模式/H5 暗夜模式的UI bugs.docx
下午5:42:35 | 进度：43.8% 起点/UI bugs/暗夜模式/iOS 暗夜模式的UI bugs.docx
下午5:42:51 | 进度：44.6% 起点/UI bugs/暗夜模式/副本 Android 暗夜模式的UI bugs.docx
下午5:43:26 | 进度：45.4% 起点/UI bugs/暗夜模式/Android 暗夜模式的UI bugs.docx
下午5:43:41 | 进度：46.2% 起点/UI bugs/V3.3.0/Android_UI bugs v3.3.0.docx
下午5:44:02 | 进度：46.9% 起点/UI bugs/V3.3.0/iOS_UI bugs v3.3.0.docx
下午5:44:22 | 进度：47.7% 起点/UI bugs/V3.3.0/原版 Android_UI bugs v3.3.0.docx
下午5:44:42 | 进度：48.5% 起点/UI bugs/V3.3.0/原版 iOS_UI bugs v3.3.0.docx
下午5:45:02 | 进度：49.2% 起点/UI bugs/V3.1.0/原版 iOS_UI bugs v3.1.0.docx
下午5:45:27 | 进度：50.0% 起点/UI bugs/V3.1.0/原版 Android_UI bugs v3.1.0.docx
下午5:46:01 | 进度：50.8% 起点/UI bugs/V3.1.0/iOS_UI bugs v3.1.0.docx
下午5:46:19 | 进度：51.5% 起点/UI bugs/V3.1.0/Android_UI bugs v3.1.0.docx
下午5:46:36 | 进度：52.3% 起点/UI bugs/V3.0/原版本iOS_GH UI bugs v3.0.docx
下午5:47:35 | 进度：53.1% 起点/UI bugs/V3.0/原版本Android_GH UI bugs v3.0.docx
下午5:48:35 | 进度：53.8% 起点/UI bugs/V3.0/iOS_GH UI bugs v3.0.docx
下午5:49:10 | 进度：54.6% 起点/UI bugs/V3.0/Android_GH UI bugs v3.0.docx
下午5:49:31 | 进度：55.4% 起点/iOS小组/例会/存档/副本 2020-04-28.xlsx
下午5:49:47 | 进度：56.2% 起点/iOS小组/例会/存档/副本 2020-04-13.xlsx
下午5:50:02 | 进度：56.9% 起点/iOS小组/例会/存档/副本 2020-04-07.xlsx
下午5:50:18 | 进度：57.7% 起点/iOS小组/例会/存档/副本 2020-03-30.xlsx
下午5:50:34 | 进度：58.5% 起点/iOS小组/例会/存档/副本 2020-03-24.xlsx
下午5:50:50 | 进度：59.2% 起点/iOS小组/例会/存档/副本 2020-03-09.xlsx
下午5:51:06 | 进度：60.0% 起点/iOS小组/例会/存档/副本 2020-02-23.xlsx
下午5:51:22 | 进度：60.8% 起点/iOS小组/例会/存档/副本 2020-01-28.xlsx
下午5:51:38 | 进度：61.5% 起点/iOS小组/例会/存档/副本 2020-01-12.xlsx
下午5:51:54 | 进度：62.3% 起点/iOS小组/例会/存档/副本 2020-01-05.xlsx
下午5:52:10 | 进度：63.1% 起点/iOS小组/例会/存档/副本 2020-12-23.xlsx
下午5:52:26 | 进度：63.8% 起点/iOS小组/例会/存档/副本 2020-12-15.xlsx
下午5:52:42 | 进度：64.6% 起点/iOS小组/例会/存档/副本 2020-11-26.xlsx
下午5:52:58 | 进度：65.4% 起点/iOS小组/例会/存档/副本 2020-10-30.xlsx
下午5:53:14 | 进度：66.2% 起点/iOS小组/例会/存档/副本 2020-09-08.xlsx
下午5:53:30 | 进度：66.9% 起点/iOS小组/例会/存档/副本 2020-5-19.xlsx
下午5:54:45 | API返回JSON解析失败：TypeError: Cannot read property 'length' of undefined
下午5:54:45 | 重试：1
下午5:55:01 | 重试成功：起点/iOS小组/例会/存档/副本 2020-5-19
下午5:55:01 | 进度：67.7% 起点/iOS小组/例会/存档/副本 2020-5-19.xlsx
下午5:55:17 | 进度：68.5% 起点/iOS小组/例会/存档/副本 2020-5-6.xlsx
下午5:56:33 | API返回JSON解析失败：TypeError: Cannot read property 'length' of undefined
下午5:56:33 | 重试：1
下午5:56:48 | 重试成功：起点/iOS小组/例会/存档/副本 2020-5-6
下午5:56:48 | 进度：69.2% 起点/UI bugs/V1.0~V2.4/V2.4/iOS_GH UI bugs v2.4.docx
下午5:57:06 | 进度：70.0% 起点/UI bugs/V1.0~V2.4/V2.4/Android_GH UI bugs v2.4.docx
下午5:57:23 | 进度：70.8% 起点/UI bugs/V1.0~V2.4/V2.3/Android_GH UI bugs v2.3.docx
下午5:57:42 | 进度：71.5% 起点/UI bugs/V1.0~V2.4/V2.3/iOS_GH UI bugs v2.3.docx
下午5:58:01 | 进度：72.3% 起点/UI bugs/V1.0~V2.4/V2.2/Android_GH UI bugs v2.2.1.docx
下午5:58:21 | 进度：73.1% 起点/UI bugs/V1.0~V2.4/V2.2/iOS_GH UI bugs v2.2.1.docx
下午5:58:41 | 进度：73.8% 起点/UI bugs/V1.0~V2.4/V2.2/Android_GH UI bugs v2.2.docx
下午5:59:01 | 进度：74.6% 起点/UI bugs/V1.0~V2.4/V2.2/iOS_GH UI bugs v2.2.docx
下午5:59:22 | 进度：75.4% 起点/UI bugs/V1.0~V2.4/V2.1/iOS_GH UI bugs v2.1.docx
下午5:59:39 | 进度：76.2% 起点/UI bugs/V1.0~V2.4/V2.1/Android_GH UI bugs v2.1.docx
下午5:59:58 | 进度：76.9% 起点/UI bugs/V1.0~V2.4/V2.0/Android_GH UI bugs v2.0.2.docx
下午6:00:15 | 进度：77.7% 起点/UI bugs/V1.0~V2.4/V2.0/GH iOS UI bugs v2.0.2.docx
下午6:00:33 | 进度：78.5% 起点/UI bugs/V1.0~V2.4/V2.0/Android_GH UI bugs v2.0.docx
下午6:01:03 | 进度：79.2% 起点/UI bugs/V1.0~V2.4/V2.0/GH iOS UI bugs v2.0.docx
下午6:01:30 | 进度：80.0% 起点/UI bugs/V1.0~V2.4/V1.9/Android_GH UI bugs v1.9.docx
下午6:01:51 | 进度：80.8% 起点/UI bugs/V1.0~V2.4/V1.9/GH iOS UI bugs v1.9.docx
下午6:02:12 | 进度：81.5% 起点/UI bugs/V1.0~V2.4/V1.8/GH iOS UI bugs v1.8.docx
下午6:02:29 | 进度：82.3% 起点/UI bugs/V1.0~V2.4/V1.8/Android_GH UI bugs v1.8.docx
下午6:02:49 | 进度：83.1% 起点/UI bugs/V1.0~V2.4/V1.7/GH iOS UI bugs v1.7.2.docx
下午6:03:06 | 进度：83.8% 起点/UI bugs/V1.0~V2.4/V1.7/Android_GH UI bugs v1.7.2.docx
下午6:03:22 | 进度：84.6% 起点/UI bugs/V1.0~V2.4/V1.7/GH iOS UI bugs v1.7.docx
下午6:03:40 | 进度：85.4% 起点/UI bugs/V1.0~V2.4/V1.7/Android_GH UI bugs v1.7.docx
下午6:04:00 | 进度：86.2% 起点/UI bugs/V1.0~V2.4/V1.6/Android_GH UI bugs v1.6.docx
下午6:04:16 | 进度：86.9% 起点/UI bugs/V1.0~V2.4/V1.6/GH iOS UI bugs v1.6.docx
下午6:04:33 | 进度：87.7% 起点/UI bugs/V1.0~V2.4/V1.5/GH iOS UI bugs v1.5.docx
下午6:04:50 | 进度：88.5% 起点/UI bugs/V1.0~V2.4/V1.5/android_GH UI bugs v1.5.docx
下午6:05:07 | 进度：89.2% 起点/UI bugs/V1.0~V2.4/V1.4/android_GH UI bugs v1.4.docx
下午6:05:27 | 进度：90.0% 起点/UI bugs/V1.0~V2.4/V1.4/GH iOS UI bugs v1.4.docx
下午6:05:47 | 进度：90.8% 起点/UI bugs/V1.0~V2.4/V1.3.2/GH iOS UI bugs v1.3.2.docx
下午6:06:05 | 进度：91.5% 起点/UI bugs/V1.0~V2.4/V1.3.2/android_GH UI bugs v1.3.2.docx
下午6:06:24 | 进度：92.3% 起点/UI bugs/V1.0~V2.4/V1.3.0/android_GoveeHome UI bugs v1.3.0.docx
下午6:06:40 | 进度：93.1% 起点/UI bugs/V1.0~V2.4/V1.3.0/GoveeHome iOS UI bugs v1.3.0.docx
下午6:06:57 | 进度：93.8% 起点/UI bugs/V1.0~V2.4/V1.2.1/GoveeHome iOS UI bugs v1.2.docx
下午6:07:13 | 进度：94.6% 起点/UI bugs/V1.0~V2.4/V1.2.1/android_GoveeHome UI bugs v1.2.1.docx
下午6:07:29 | 进度：95.4% 起点/UI bugs/V1.0~V2.4/V1.2/android_GoveeHome UI bugs v1.2.docx
下午6:07:44 | 进度：96.2% 起点/UI bugs/V1.0~V2.4/V1.2/GoveeHome iOS UI bugs v1.2.docx
下午6:08:01 | 进度：96.9% 起点/UI bugs/V1.0~V2.4/V1.1/android_GoveeHome UI bugs v1.1.docx
下午6:08:17 | 进度：97.7% 起点/UI bugs/V1.0~V2.4/V1.1/GoveeHome iOS UI bugs v1.1.docx
下午6:08:34 | 进度：98.5% 起点/UI bugs/V1.0~V2.4/V1.0/GoveeHome iOS UI bugs.docx
下午6:08:50 | 进度：99.2% 起点/UI bugs/V1.0~V2.4/V1.0/GoveeHome Android UI bugs.docx
下午6:09:06 | 导出工作结束，失败数：0
下午6:09:06 | 总用时：57.6 分钟。
下午6:09:06 | 正在生成 zip 文件

**Comment by ihomentMickChen** [comment]
你好，我修改了脚本代码，主要是增加了下载超时时间、重试次数。然后变更了压缩文件的下载方式，请查看下述文档，如有侵权可删除
https://github.com/ihomentMickChen/shimo

**Comment by gordonwalkedby** [comment]
@ihomentMickChen   你那个自己觉得好用就行。我只是觉得你应该是个大学生。     
至于那些修改什么的，我就不看了。

**Comment by lifegpc** [comment]
> @ihomentMickChen 你那个自己觉得好用就行。我只是觉得你应该是个大学生。
> 至于那些修改什么的，我就不看了。

xswl
