### ISSUE TITLE
大佬这个解析失败是正常的是吧

### ISSUE THREAD

**Issue by CharlesYe8848** [gordonwalkedby/shimo-export#5]
![image](https://user-images.githubusercontent.com/26808857/124556719-3232f780-de6b-11eb-8cd1-fcba238a2b6a.png)

**Comment by gordonwalkedby** [comment]
这很明显是不正常的。      
我很好奇你这个 /sheet/ 和 /doc/ /spreadsheet/ 是哪里来的     
我们的石墨链接都是 /sheets/   /docs/  /presentation/
